name: Deploy application (PRD)

on:
  workflow_dispatch:
    inputs:
      forceDeployment:
        description: Force infrastructure deployment if the last infrastructure template used is the same as the current one
        required: false
        default: false
        type: boolean

concurrency: deploy_app_prd

env:
  INFRA_TYPE: 'monitoring'
  INFRA_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.prd.json'
  INFRA_RG_NAME: 'mil-monitoring-prd-rg'
  INFRA_RG_LOCATION: 'westeurope'
  TEMPLATES_VERSION: v8

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - uses: actions/checkout@v3 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v3
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          scopeLocation: ${{ env.INFRA_RG_LOCATION }}
          templateType: ${{ env.INFRA_TYPE }}
          parametersFilePath: ${{ env.INFRA_PARAMETERS_PATH }}
          forceDeployment: ${{ github.event.inputs.forceDeployment }}
